export const SIGN_IN_PATH = '/login'
export const ADMIN_PAGE_PATH = '/admin'
export const USER_PAGE_PATH = '/user'
export const CREATE_FORM_PATH = '/create'
export const RESULT_RESPONSE_PATH = '/results'
export const PREVIEW_FORM = '/forms/:formId/preview'
